// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Radar.Migrations
{
    [DbContext(typeof(RadarContext))]
    partial class RadarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("TestResult", b =>
                {
                    b.Property<DateTime>("RanAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Download")
                        .HasColumnType("REAL");

                    b.Property<bool>("HasSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Long")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Ping")
                        .HasColumnType("REAL");

                    b.Property<double>("Upload")
                        .HasColumnType("REAL");

                    b.HasKey("RanAt");

                    b.ToTable("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
